version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - pip install pytest
  build:
    commands:
      # Build and run tests to make sure all ok
      - pip install -r source/requirements_dev.txt
      - pytest

  post_build:
    commands:
    # Create the build package
      - echo creating package
      - mkdir buildoutput
    # The requirements build for production
      - pip install -r source/requirements_lambda.txt  -t source
      - cd source && zip -r ../buildoutput/pytorchzip_lambda_deployment_package.zip . -x test* && cd ..


artifacts:
  files:
    - '**/*'
  base-directory: buildoutput